### ISSUE TITLE
Future releases? (0.13)

### ISSUE THREAD

**Issue by ebukoski** [OpenGrok/OpenGrok#1084] opened 2016-04-06 00:14 UTC
There hasn't been a new release of OpenGrok since March 2015.  

Any chance that there is a new release coming soon? Or has the release model been abandoned?

**Comment by tarzanek** [comment] 2016-04-06 04:18
No
We work on a release and it's long overdue.
I hesitate to give my go because there are still some stoppers and the scopes need a redesign to mitigate performance impact.
However we might need to release 0.13 as is and document this impact or add a flag to disable scopes to avoid this index creation performance regression
...
I will post some links to bugs you can help with or testing to expedite the release.

**Comment by vladak** [comment] 2016-04-07 12:44
It seems that we suffer a little bit from feature creep however there are some things which just have to go in :-) before the release, like the authorization framework #1083 which we need for internal deployment.
Also, there is number of stoppers which have to be addressed. Like with every release, someone starts by saying that we should release in this or that time frame and the reality usually differs by a large margin (similarly to what happens to Elon Musk as well :-)).

We can use this issue as a placeholder for listing the criteria for the release and related discussion.

**Comment by vladak** [comment] 2016-04-11 15:32
Also, we can start publishing pre-releases like we did with 0.12.

**Comment by vladak** [comment] 2016-05-06 08:51
We are now down to 4 stoppers.

**Comment by tarzanek** [comment] 2016-05-19 19:31
fwiw one stopper left ...

**Comment by ebukoski** [comment] 2016-05-19 19:51
Nice!  Glad to hear it is progressing.

**Comment by vladak** [comment] 2016-05-24 12:09
I believe the original question was answered, closing.

**Closed by vladak** 2016-05-24 12:09 UTC
Labels: question
