### ISSUE TITLE
hg historycache generation failed. Why ?

### ISSUE THREAD

**Issue by Hieronim99** [OpenGrok/OpenGrok#1713] opened 2017-08-01 16:55 UTC
Hi,
I have question regarding searching history. It doesn't work ;)
Environment:
VirtualMachine with Ubuntu 14.04, OpenGrok 1.1rc5, tomcat 8.0.32-1ubuntu1.4, jdk oracle 1.8.0_131, Mercurial 3.7.3
Options that i use in config file:
OPENGROK_DISABLE_RENAMED_FILES_HISTORY=true
OPENGROK_GENERATE_HISTORY=on
OPENGROK_ENABLE_PROJECTS=false

Source is one directory with some couple hundred Mercurial repositories spread underneath, on several levels of nesting (meaning not all are directly under SRC_ROOT). 
During index command i get 1 warning:
WARNING: Non-zero exit status 255 from command [/usr/bin/hg, log, -r, reverse(0::'default'), --template, changeset: {rev}:{node|short}\nuser: {author}\ndate: {date|isodate}\ndescription: {desc|strip|obfuscate}\nfiles: {files}\nmercurial_history_end_of_entry\n] in directory <local repo directory>: abort: unknown revision 'default'!

18:42:59 WARNING: An error occured while creating cache for <local repo directory> (MercurialRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "<local repo directory>" Exit code: 255

plus 4: WARNING: Cannot write latest cached revision to file for <another local repo dir>
java.io.FileNotFoundException: /home/whitelab/opengrok-ci/data/historycache/DRM/Cubiware/ConaxLibraryCore/QBConaxCardDriverHAL/OpenGroklatestRev 

I can access annotate view, compare revisions and list history log in repositories but history search just won't work.

Thanks for any suggestions.

**Comment by vladak** [comment] 2017-08-01 19:40
What is Mercurial version you're running ? is there anything special about these repositories ? Does this happen for all of them or just for some ?

**Comment by vladak** [comment] 2017-08-01 19:55
The second warning about the `OpenGroklatestRev` file is likely related to #1297 - basically the message is displayed if no history can be acquired for given repository. The issue is fixed in 1.1-rc6 I think.

**Comment by Hieronim99** [comment] 2017-08-01 23:22
It's hard to check manually all of 600+ repos, checked couple of them (open the history, copy the commit msg, search for it - nothing can be found).
Mercurial 3.7.3 localside, server side <3.0, i think even below 2.8.

**Comment by Hieronim99** [comment] 2017-08-01 23:26
Server theoretically might not allow hg access for tomcat/opengrok. 
Though if history is available locally (and it is, as i manually pull before index) would that prohibit creating history cache?

**Comment by vladak** [comment] 2017-08-02 09:29
Depends on what user the `hg log` command is run under. Try switching to the user the indexer is running as and run the `hg log -r 'reverse(0::'default')'` command in one of the repositories where it failed.

**Comment by vladak** [comment] 2017-10-02 16:48
No response for couple months, closing.

**Closed by vladak** 2017-10-02 16:48 UTC
Labels: question
