### ISSUE TITLE
Failed to create index when there are long lines with 700000+ chars in one line in a file

### ISSUE THREAD

**Issue by doris2012** [OpenGrok/OpenGrok#922] opened 2015-03-30 06:51 UTC
we have a file with two line which have 7000000+ chars in one line, and when we run ./OpenGrok index , it have been pending. 

I tried to deleted the two lines, it quickly to generate index.

I wonder if there is any settings to fix the problem?

**Comment by tarzanek** [comment] 2015-03-30 09:51
this smells like ctags problem
what is the head -3 of the file and its file name (extension?) ?

**Comment by vladak** [comment] 2016-10-06 15:19
Also see #1170

**Comment by tarzanek** [comment] 2016-10-09 11:51
well ... I think I can safely close this as as duplicate of #1170 
@doris2012 please reopen if it's something else

**Closed by tarzanek** 2016-10-09 11:51 UTC
