### ISSUE TITLE
better repository table formatting in presence of big column widths

### ISSUE THREAD

**Issue by ChristopheBordieu** [OpenGrok/OpenGrok#1478] opened 2017-03-22 18:46 UTC
Hello
With 0.13-rc10, I manage many projects with, for each, many repos inside, with some repo paths very long.
Result is that in homepage, Mirror column is very large leading to colum Current version splitted on several lines.  Thus, each line for project or repo is very high.

![capture](https://cloud.githubusercontent.com/assets/26546513/24215096/f2a6519a-0f37-11e7-8887-f975b70b8515.PNG)

The root cause is that, by default, all repos into a project are displayed.
Is it possible to fold all projects by default ? And to unfold only clicked project ?

**Comment by tulinkry** [comment] 2017-03-28 14:02
It should be possible to limit the scan to only top level directories with this for the wrapper:
```txt
#   - OPENGROK_SCAN_DEPTH         how deep should scanning for repos go
#                                 (by default 3 directories from SRC_ROOT)
```
or this with java
```bash
# options.add(new Option('z', NUMBER, "depth of scanning for repositories in directory structure relative to source root. Default is "+Configuration.defaultScanningDepth+" ."));
java -jar opengrok.jar -z 1
```

You loose the subrepository listing with this; it's not folded/hidden or anything like that.

**Comment by ChristopheBordieu** [comment] 2017-03-28 15:25
But I want to scan my project dirs to get repos inside. My OPENGROK_SCAN_DEPTH is set to 2 for that purpose: all repos are level 2 below SRC_ROOT.
Not sure I understand your comment...
I would like the UI offers the possibility to fold or not the project directory, not showing or showing the repos inside. Default would be not showing the repos. Then clicking for example to a project, repos will be unfolded and showed.
Sorry, maybe me explanation (in French English) is not clear.

**Comment by tulinkry** [comment] 2017-03-28 15:34
Yes I understood the problem. I just tried to offer you a temporary workaround before this gets fixed in master. However you use that intentionally so it's not a solution for you.

**Comment by ChristopheBordieu** [comment] 2017-06-27 20:13
Hello,
Is there any news regarding this UI bug ?

**Comment by ChristopheBordieu** [comment] 2017-07-07 20:09
Hello,
I have played with groups thinking it could help me to get the folding feature I was requesting when entering this issue.
Actually, there is indeed a bug. I have not noticed it because I was focused on display...
So, I  explain again. M?aybe it will help you to reproduce the issue.
The structure of my src directory is:
SRC/
  projA/
      repoA1
      repoA2
      repoA3
  ProjB/
       repoB1
  projC/
       repoC1
       repoC2
   ...

I am not sure to understand now what is a project in the OpenGrok wording...

When I index, the home page displays this:
Mirror                    SCM Type: Parent (branch)
projA                     urltoprojArepoA1
    projA/repoA2    urltoprojArepoA2
    projA/repoA3    urltoprojArepoA3
projB                      urltoprojBrepoB1  
projC                      urltoprojCrepoC1
     projC/repoC2    urltoprojCrepoC2
     projC/repoC3    urltoprojCrepoC3

According to my partial understanding of what is an OpenGrok project, I am expecting that the first repo of each of my project is displayed exactly the same way as the remaining repos of that same project. Ie, I expect display of homepage to be::
Mirror                SCM Type: Parent (branch)
projA/repo1      urltoprojArepoA1
projA/repoA2    urltoprojArepoA2
projA/repoA3    urltoprojArepoA3
projB                 urltoprojBrepoB1  
projC/repoC1   urltoprojCrepoC1
projC/repoC2    urltoprojCrepoC2
projC/repoC3    urltoprojCrepoC3

Am I right ?
What is really an OpenGrok project ? In the Select project box, only projA, projB and projC are available.

I was able, after some fight, to define groups named like my projects projA, projB and projC. I was happy because I have now a page with folded list of repos per project.
But I still have the same display issue for each group. I get this:

projA [select all] (0+1)
Mirror                    SCM Type: Parent (branch)
projA                     urltoprojArepoA1
    projA/repoA2    urltoprojArepoA2
    projA/repoA3    urltoprojArepoA3

projB [select all] (0+1)
Mirror                    SCM Type: Parent (branch)
projB                      urltoprojBrepoB1  

projC [select all] (0+1)
Mirror                    SCM Type: Parent (branch)
projC                      urltoprojCrepoC1
     projC/repoC2    urltoprojCrepoC2
     projC/repoC3    urltoprojCrepoC3

Hope this clarifies... Regarding the group, I have questions I will ask in a separate issue.
Thanks for your feedback.

**Comment by vladak** [comment] 2017-07-08 07:39
Project in opengrok is a subdirectory under source root that can contain zero or more repositories. Project can have properties (e.g. tab size etc.)

**Comment by vladak** [comment] 2017-07-08 07:42
W.r.t. scaling of the display you are right, we thought in terms of hundreds not thousands of projects.

**Comment by ChristopheBordieu** [comment] 2017-07-10 12:31
Hello
- Could you confirm the display I have has a bug ?
- Also, is there a way to get rid of the display of all repos ? I put in prod 1.1-rc5 and users don t like the fact homepage is displayed after 8s because of the numbers of repos... Can I add some code into body_include (without .html) that would cancel the dynamic computation and display of repo list ? That would be an acceptable workaround for us. Eventually waiting for a parameter that would allow to disable repo list.

**Comment by ChristopheBordieu** [comment] 2017-07-11 09:01
Regarding what I consider a bug, found into _repos.jspf_ that the variable _cnt_ could eventually be badly initialized to 0, instead of 1. If initialized to 1, display (with or without groups) is now correct: no special treatment for first repo of each project.

````
...
149                         Integer cnt = 1;
...
279                             Integer cnt = 1;
...
``

**Comment by ChristopheBordieu** [comment] 2017-08-01 11:57
Hello,
May I have your feedback regarding my various questions/comments ? Do you want me to open dedicated issues for enhancement or bug ?

**Comment by vladak** [comment] 2017-08-04 08:19
As for getting rid of the display of all projects/repos - this is easy to do, pls file a separate issue for that and ideally submit a pull request - it's just a trivial modification of RuntimeEnvironment/Configuration and `repos.jspf`.

**Comment by vladak** [comment] 2017-08-04 09:34
Actually, just submitted a pull request #1718 for the tunable.

**Comment by vladak** [comment] 2017-08-04 10:09
As for the JavaScript based workaround - I think you can just undo the display of the repositories after they are displayed which is of no use as the time was already lost rendering the page when JS comes to run. There is no way how to influence the creation of the page on the client side since `repos.jspf` is static JSP include. The `displayRepositories` tunable provided by the above pull request will provide the functionality on server side.

**Comment by ChristopheBordieu** [comment] 2017-08-04 10:13
ok. and regarding the integer Count = 0 ? do you confirm it is a bad init value?

**Comment by vladak** [comment] 2017-08-04 11:04
As far as the indentation of nested repositories go, this is definitely intentional - the sub-repositories being indented to the right relative to the first (top-level) repository cause that helps orientation.

**Comment by vladak** [comment] 2017-08-04 11:10
I think the real issue here is the formatting/display of the table. I can get into similar situation even without projects with deep nesting level of repositories, e.g.:

![table](https://user-images.githubusercontent.com/2934284/28966333-d27a372c-7915-11e7-8e91-9ce6e76c6532.png)

The 'Current version' column is 400px by default in `style.css`:

```
.panel-body > table tr td:last-child, .panel-body-accordion > table tr td:last-child {
    width: 400px;
}
```

however it seems this gets pushed out if the other columns get wider and their content cannot be wrapped (as is the case of long repository paths/names).

Possibly the contents can be truncated (with mouse over or 'show more' displaying the full content) or wrapped differently (according to broader set of characters, not just whitespace).

**Comment by vladak** [comment] 2017-08-04 11:29
The `cnt` value initialized to 0 is intentional as I wrote above. After all. the `repos.jspf` contains this:

```
<td class="name <%= cnt > 0 ? "subrepository" : "repository" %>">
```

If `cnt` was always strictly greater than zero, the `repository` CSS style would be useless and everything will be padded:

```
.projects .subrepository {
    padding-left: 20px;
}
```

possibly aggravating the problem with long content.

Besides, without it starting with 0, projects with no parents would not be displayed at all which is wrong.

**Comment by ChristopheBordieu** [comment] 2017-08-04 11:36
ok. but so, why I get what i described on my comment on July 7th ?

**Comment by vladak** [comment] 2017-08-04 11:50
You mean the behavior with groups ?

**Comment by ChristopheBordieu** [comment] 2017-08-04 12:05
No. The fact that, without or with group, the very first repo of each of my projects is never displayed with full path: 
```
Mirror              SCM Type: Parent (branch)
projA               urltoprojArepoA1
    projA/repoA2    urltoprojArepoA2
    projA/repoA3    urltoprojArepoA3
projB               urltoprojBrepoB1  
projC               urltoprojCrepoC1
    projC/repoC2    urltoprojCrepoC2
    projC/repoC3    urltoprojCrepoC3
```

I am expecting this dislay:
```
Mirror          SCM Type: Parent (branch)
projA/repoA1    urltoprojArepoA1
projA/repoA2    urltoprojArepoA2
projA/repoA3    urltoprojArepoA3
projB/repoB1    urltoprojBrepoB1  
projC/repoC1    urltoprojCrepoC1
projC/repoC2    urltoprojCrepoC2
projC/repoC3    urltoprojCrepoC3
```

**Comment by vladak** [comment] 2017-08-04 12:15
That might be a bug, pls file a separate issue for it with steps to reproduce.

**Comment by ChristopheBordieu** [comment] 2017-08-04 12:23
ok. will do that.

**Closed** 2017-08-07 16:24 UTC
Labels: bug
