### ISSUE TITLE
Source code annotation culumns are too thin 

### ISSUE THREAD

**Issue by Hlipa** [OpenGrok/OpenGrok#1356] opened 2017-01-30 15:41 UTC
![grok](https://cloud.githubusercontent.com/assets/5871295/22429651/8d1c986a-e70b-11e6-8f94-88f3e3e6627f.png)
Source code annotation columns are too thin. Changeset number is trimmed (maybe is overwritten by next column) and author name overlap into code.  FF 45.7 (chrome works better, but still not optimal)

**Comment by tulinkry** [comment] 2017-02-06 15:36
Does this happen even when you clear the browser's cache? (Ctrl+shift+delete on FF)

**Comment by tulinkry** [comment] 2017-02-06 15:45
Does this happen after you clear the browser's cache? (ctrl+shift+delete on FF)?

**Comment by tulinkry** [comment] 2017-02-07 14:26
It happend to me also. The content is missing [this output](https://github.com/OpenGrok/OpenGrok/blob/master/web/list.jsp#L59-L62):
```java
        cfg.addHeaderData("<style type=\"text/css\">"
            + ".blame .r { width: " + (r == 0 ? 6 : r) + "ex; } "
            + ".blame .a { width: " + (a == 0 ? 6 : a) + "ex; } "
            + "</style>");
```

Need to investigate it further

**Comment by tulinkry** [comment] 2017-02-08 13:17
Duplicate of #669

**Closed** 2017-02-09 16:24 UTC
Labels: bug, stopper
