### ISSUE TITLE
Full search result missed few char to display

### ISSUE THREAD

**Issue by bhkoteshwar** [OpenGrok/OpenGrok#941] opened 2015-05-20 01:47 UTC
While performing the full search of the text, last few char of the the search word not displaying in the search result.

Example: 
File content:
--------------
xxxxx
yyyyyyyy
zzzzzzzzzzz
include-in-xxyyzzwords=abcd

Search key word in full search:
--------------------------------------
include-in-xxyyzzwords=abcd

Search result:
-----------------
1 xxxxx
2 yyyyyyyy
3 zzzzzzzzzzz
4 include-in

**Comment by tarzanek** [comment] 2015-05-20 13:02
can you search and enclose your string in "" ?
"include-in-xxyyzzwords=abcd"
it should yield wanted results, without "" the string in search is parsed and e.g. "-" and "=" are parsed out
I will try to reproduce, since 1-3 results are buggy for sure

**Comment by Arenking** [comment] 2015-05-20 13:23
Hi tarzanek,

it was me that reported the error to bhkoteshwar.
I got the issue by making a Full Search for "include-in-build=true"

The response I got was:
filename_A      include-in-build=true
filename_B      include-in-build=tru
filename_C      include-in-build=true
filename_D      include-in-build=tru
filename_E      include-in-build=true

What filename_B and filename_D had in common was that "true" was the very last thing in the file.
All other files had a linebreak after the "true".
Therefore I believe the issue happens only when searching for the very last word in a file.

BR;
Arenking

**Comment by tarzanek** [comment] 2015-05-20 14:30
seems like bug with EOF then ... @kahatlen any ideas?
since you got the hit I think only the highlighter - summarizer is faulty 
guess someone will have to rewrite it to use lucene highlighter finally

**Comment by kahatlen** [comment] 2015-06-13 20:59
What kind of file is filename_B and filename_D? I cannot reproduce this when I create a file called test.txt with the contents mentioned in the bug report, and with no newline after the last line. But that only tests the plain text analyzer. There may still be a bug in one of the analyzers for some specific language.

Also, how big are filename_B and filename_D? The summarizer only looks at the first 1MB of the file, so there could be some display bug if the match happens to cross the 1MB border. I didn't see any problem with that in my tests, though.

**Comment by Arenking** [comment] 2015-06-15 07:17
Filenames were "*.properties"
Files were short, maximum 15 short rows.

I tried to reproduce it both yesterday and today, but I do not get the problem anymore.
Strange, cause I did get it 10 times out of 10 when I found it.

Anway, you can close this issue for now, and I get back if I get the problem again.

**Closed** 2015-06-15 08:17 UTC
Labels: bug
