### ISSUE TITLE
file error halt search result output

### ISSUE THREAD

**Issue by xuefer** [OpenGrok/OpenGrok#1341] opened 2017-01-22 04:35 UTC
let's ignore why this file is Permission denied (or not found), but this error is breaking search result. search results shows files before but not after this error
please just show or ignore the error and go on listing all other results
```
java.io.FileNotFoundException: /home/xuefer/src/chromium/src/build/linux/debian_wheezy_i386-sysroot/usr/lib/gcc/i486-linux-gnu/4.6/include/ia32intrin.h (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.opensolaris.opengrok.search.Results.prettyPrint(Results.java:233)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:822)
	at org.apache.jasper.runtime.HttpJspBase.service(Unknown Source)
	at javax.servlet.http.HttpServlet.service(Unknown Source)
	at org.apache.jasper.servlet.JspServletWrapper.service(Unknown Source)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(Unknown Source)
	at org.apache.jasper.servlet.JspServlet.service(Unknown Source)
	at javax.servlet.http.HttpServlet.service(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
	at org.opensolaris.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
	at org.apache.catalina.core.StandardWrapperValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardContextValve.invoke(Unknown Source)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Unknown Source)
	at org.apache.catalina.core.StandardHostValve.invoke(Unknown Source)
	at org.apache.catalina.valves.ErrorReportValve.invoke(Unknown Source)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardEngineValve.invoke(Unknown Source)
	at org.apache.catalina.connector.CoyoteAdapter.service(Unknown Source)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(Unknown Source)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vladak** [comment] 2017-01-23 09:46
duplicate of #986

**Closed by vladak** 2017-01-23 09:46 UTC
