### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by andycoolware** [OpenGrok/OpenGrok#852] opened 2014-07-28 16:53 UTC
Environment: OpenGrook 0.12.1, Linux, Java 7 64-bit, >JAVA_OPTS="-Xmx16g -Xms16g"<

Scanning about 300 projects, small , to medium size, total 20GB of all source code
Scan results with "java.lang.OutOfMemoryError: Requested array size exceeds VM limit"

**Comment by tarzanek** [comment] 2015-06-21 12:33
fwiw, #508 has improved the ignore option!

**Comment by mskim77** [comment] 2015-07-29 23:32
08:28:41 SEVERE: Problem updating lucene index database:
I'm on the same errors...

**Comment by tarzanek** [comment] 2015-07-30 09:48
yes yes, I need to writeup the memory limiter code for ctags, will try to do it, this hangs in the air for too long now ... :(

**Comment by tarzanek** [comment] 2015-07-30 09:49
@mskim77 if you know which file caused it, get it to ignore for now
also note that bcel component is buggy with jdk8(7 too?) until they release 6.x so tar/zip files will fail because of their size, jar/class files will fail because of bcel ... 
ignore them for quick relief

**Comment by tarzanek** [comment] 2015-07-30 09:51
hmm, actually good news at least for bcel, it seems 6.0 rc4 was released on 24. July, so we will hopefully see 6.0 soonish

**Comment by ratemyduck** [comment] 2016-03-27 20:33
Is this the same error, or is it unrelated?

`18:57:41 SEVERE: Problem updating lucene index database: 
java.lang.OutOfMemoryError
        at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
        at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.opensolaris.opengrok.analysis.Definitions.serialize(Definitions.java:196)
        at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:82)
        at org.opensolaris.opengrok.analysis.plain.AbstractSourceCodeAnalyzer.analyze(AbstractSourceCodeAnalyzer.java:69)
        at org.opensolaris.opengrok.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:307)
        at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:606)
`

As far as I can see it tries to create an byte array that is longer than Integer.MAX while trying to serialize definitions. 

Would it be a good idea to apply the workaround suggested here?

**Comment by tarzanek** [comment] 2016-03-29 12:53
@ratemyduck yes, please use ignore option for the file which causes it
can you eventually share the file?

**Comment by tarzanek** [comment] 2016-07-29 08:59
fwiw I am tempted to close this, with ctag fixes in trunk and latest bcel I think this won't reproduce anymore ...

**Comment by ratemyduck** [comment] 2016-07-31 10:26
I cannot help, we do not run Opengrok anymore. As a general note, 2014 is a long time ago, closing it seems resonable.

**Closed** 2016-07-31 18:55 UTC

**Comment by fairmonk** [comment] 2016-12-14 09:35
Hi I know it's a closed topic, but since I have same error as ratemyduck posted here, I'll give it a try.
**Problem** OOM error; **Question**: how to identify which file is causing the OOM in order to exclude it
Here is my command I run for reindexing:
java -Xmx28g -jar C:\grok_0.12.1\opengrok-0.12.1.6\lib\opengrok.jar -W C:\grok_0.12.1\Data\configuration.xml -c C:\grok_0.12.1\ctags58\ctags.exe -P -S -v -s C:\grok_0.12.1\src -d C:\grok_0.12.1\Data -i *.zip -i *.tmp -i *.db -i *.jar -i *.class -i *.dylib -i d:.svn -G -L polished -a on -T 8

here is my log snapshot:
08:08:19 INFO: Skipped file '/UFT-trunk/QTP/Addins/Flash/FlexPackage/app/apache-flex-sdk-4-14-hp-mod/lib/aot/stub/iAd.framework/iAd' because the analyzer didn't understand it.
08:08:19 Dec 14, 2016 8:08:11 AM org.opensolaris.opengrok.index.DefaultIndexChangedListener fileRemove
08:08:19 INFO: Remove file:/UFT-trunk/QTP/Addins/Flash/FlexPackage/app/apache-flex-sdk-4-14-hp-mod/lib/aot/stub/libgcc_s.1.dylib
09:10:36 Dec 14, 2016 9:10:27 AM org.opensolaris.opengrok.index.IndexDatabase$1 run
09:10:36 SEVERE: Problem updating lucene index database: 
09:10:36 java.lang.OutOfMemoryError
09:10:36 	at java.io.ByteArrayOutputStream.hugeCapacity(Unknown Source)
09:10:36 	at java.io.ByteArrayOutputStream.grow(Unknown Source)
09:10:36 	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
09:10:36 	at java.io.ByteArrayOutputStream.write(Unknown Source)
09:10:36 	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
09:10:36 	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
09:10:36 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
09:10:36 	at java.io.ObjectOutputStream.writeObject(Unknown Source)
09:10:36 	at org.opensolaris.opengrok.analysis.Definitions.serialize(Definitions.java:196)
09:10:36 	at org.opensolaris.opengrok.analysis.plain.PlainAnalyzer.analyze(PlainAnalyzer.java:82)
09:10:36 	at org.opensolaris.opengrok.analysis.plain.AbstractSourceCodeAnalyzer.analyze(AbstractSourceCodeAnalyzer.java:69)
09:10:36 	at org.opensolaris.opengrok.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:307)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:606)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:870)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:835)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:383)
09:10:36 	at org.opensolaris.opengrok.index.IndexDatabase$1.run(IndexDatabase.java:168)
09:10:36 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
09:10:36 	at java.util.concurrent.FutureTask.run(Unknown Source)
09:10:36 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09:10:36 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09:10:36 	at java.lang.Thread.run(Unknown Source)
09:10:36 
09:10:36 Dec 14, 2016 9:10:29 AM org.opensolaris.opengrok.util.Statistics report
09:10:36 INFO: Done indexing data of all repositories (took 1:02:53)
09:10:36 Dec 14, 2016 9:10:29 AM org.opensolaris.opengrok.util.Statistics report
09:10:36 INFO: Total time: 1:02:53
09:11:24 Dec 14, 2016 9:11:16 AM org.opensolaris.opengrok.util.Statistics report
09:11:24 INFO: Final Memory: 50M/16,054M

Sorry for a quite long post.

**Comment by tarzanek** [comment] 2016-12-14 20:07
you need 0.13 ... check RCs, you won't reproduce this problem , we really have to release 0.13
I don't plan to backport that fix to 0.12 ...

**Comment by fairmonk** [comment] 2016-12-15 15:34
Thank you for the lightning fast response, I updated to RC5 as you suggested and the error is gone! Thanks a lot!
