### ISSUE TITLE
perforce problem when doing OpenGrok index update

### ISSUE THREAD

**Issue by ymnick** [OpenGrok/OpenGrok#926] opened 2015-04-03 20:26 UTC
Hi All,

I am looking for OpenGrok index update documentation, both manual and automated, please advise. Ideally I'd like to have it configured each time source files are updated, or on a scheduled basis. If not supported, manual option will do too as long as it doesn't rebuild index from scratch every time.

Thanks,
YM

**Comment by harryxp** [comment] 2015-04-03 20:32
My blog post may be helpful: http://ctrl-c.io/post/opengrok-setup

Appendix A shows you how to do it:

$ export OPENGROK_VERBOSE=true
$ export OPENGROK_PROGRESS=true # turn this off for performance
$ export OPENGROK_INSTANCE_BASE=~/og-instance-base
$ export OPENGROK_WEBAPP_CONTEXT=opengrok
$ ./OpenGrok update

If you are on a Unix-like machine, I recommend using cron to run it
periodically.  Re-index whenever the code is updated sounds too aggressive,
though I think you can do it using libevent.

**Comment by ymnick** [comment] 2015-04-03 20:40
Thank you for your prompt response! Actually I try it on Windows using this guide - http://algopadawan.blogspot.co.uk/2012/07/installing-opengrok-on-windows.html, do you know if the following command will update or recreate the index?

java -jar opengrok.jar -W G:\opengrok-0.11.1\configuration.xml -c G:\ctags58\ctags.exe -P -S -v -s G:\CodeSource -d G:\opengrok-0.11.1\grokdata

Thanks!

**Comment by harryxp** [comment] 2015-04-03 20:46
I'll defer to the maintainers to answer that since I've never done it on
Windows.  If you're interested, the OpenGrok source code Indexer.java tells
you what those flags mean (in current version):

https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/Indexer.java

BTW, I strongly recommend using the latest version of OpenGrok :)

**Comment by ymnick** [comment] 2015-04-03 20:53
Thank you!

**Comment by vladak** [comment] 2015-04-04 06:49
All the OpenGrok invocations should perform incremental reindex, so the above will work too in this respect.

**Comment by ymnick** [comment] 2015-04-08 00:36
Thank you!

**Comment by ymnick** [comment] 2015-04-09 01:31
A follow up question - what additional configuration is required to see file history instead of 'error: file not found' error message? I guess I am missing something very basic in my setup, as it shows no external repositories when I run it with '-K' flag:

Logging filehandler pattern: %h/java%u.log
...org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Scanning for repositories...
...org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Done scanning for repositories (3s)
Repositories in C:\opengrok\source:

...org.opensolaris.opengrok.util.Statistics report
INFO: Total time: 3.715 seconds
...org.opensolaris.opengrok.util.Statistics report
INFO: Final Memory: 1M/121M

**Comment by tarzanek** [comment] 2015-04-09 09:36
I guess I will have to put the windows .bat file back to Opengrok ... at least for inspiration (though ideally if OpenGrok could be used too ... M$ could finally implement a shell that works with POSIX), so options:
-S -r on
to get remote repos working ...

fwiw - my command:
set EXUB_CTAGS=C:\Programy\ctags58\ctags.exe
set PROPERTIES="-Dorg.opensolaris.opengrok.history.Mercurial=C:\Program Files\Mercurial\hg.exe"
set SCAN_FOR_REPOS="-S"
set WEBAPP="localhost:2424"
set SKIN="-Ldefault"
rem set PROPERTIES="-Dorg.opensolaris.opengrok.history.CVS=C:\sccs.bat"
set LPROPERTIES="-Djava.util.logging.config.file=logging.properties"
%JAVA_HOME%\bin\java %DEBUG% %PROPERTIES% %LPROPERTIES% -jar %PROGDIR%opengrok.jar %SKIN% -p \opengrok %WA%  -U %WEBAPP% -P -W C:\var\opengrok\etc\configuration.xml  %SCAN_FOR_REPOS% -r on %MAXWORDS% -a on -v -c %EXUB_CTAGS% -s %SRC_ROOT% -d %DATA_ROOT%

**Comment by ymnick** [comment] 2015-04-09 16:27
Thank you.

I run a very similar command - java -jar opengrok.jar -W C:\opengrok\configuration.xml -c C:\ctags\ctags.exe -P -S -r on -v -s C:\opengrok\source -d C:\opengrok\grokdata -U localhost:2424

And in the output I see a lot of this:
...org.opensolaris.opengrok.history.HistoryGuru createCache
INFO: Creating historycache for C:\opengrok\source (PerforceRepository)
...org.opensolaris.opengrok.history.Repository getHistory
WARNING: Incremental history retrieval is not implemented for PerforceRepository.
...org.opensolaris.opengrok.history.Repository getHistory
WARNING: Falling back to slower full history retrieval.

'java -jar opengrok.jar -W C:\opengrok\configuration.xml -c C:\ctags\ctags.exe -s C:\opengrok\source -d C:\opengrok\grokdata -K -v -r on' doesn't show repositories as before.

**Comment by tarzanek** [comment] 2015-04-10 11:05
-S searches for repos
the warnings are due to @vladak incremental history fixes for file based backend storage and it seems perforce doesn't have this implemented (or doesn't support it? most probably we lack logic in OpenGrok to add incr. update), I know git or hg do incremental history easily

I'd suggest you to try the same with plain OpenGrok on some linux/unix system and note down the command line options and transfer them to windows
(does perforce have a linux/unix client?)

So just to wrap up - is it working what you wanted?
I actually would be happy if someone would take care of windows start script which would mimic what linux/unix OpenGrok does ... if you dare to write OpenGrok.sh I'd be happy to provide my windows development scripts to run OpenGrok (I develop on win7 64bit enterprise, then on debian stable and on solaris latest testing) so you can polish them and port them
but frankly, I doubt Windows would scale with huge repos, so that's why I wouldn't advise running production OpenGrok on Windows ... I could be biased, but imho Solaris 11.2 is the best platform to run an opengrok server (java updates automated, with all its zfs goodnes and worst case one can deploy manual tomcat8 and don't rely on (old) tomcat6, which in S11 is very old, but I know they are going to adopt tomcat8 very very soon).

**Comment by ymnick** [comment] 2015-04-10 16:16
Thanks @tarzanek. This Windows installation is for POC purposes only and I'd like to make it working with History and Annotations, but at this moment it is not. I tried to modify the following line in bin/OpenGrok from 'P4="`Which p4`"' to 'P4="C:\Program Files\Perforce\p4.exe"' but that didn't help either.

I should be able to try it on Linux soon and update with my findings.

Thanks again,
@ymnick

**Comment by tarzanek** [comment] 2015-04-13 08:42
well, @trondn was the last one from commiters who had working perforce history ... @trondn can you whip together a how to on perforce + opengrok?

**Comment by trondn** [comment] 2015-04-13 09:49
Unfortunately it's been waaaaay too long ago for me to remember (and I don't have that computer anymore...) The normal way to debug this is to try to run all of the same commands OpenGrok runs from the command line, and then you'll see all of the errors it prints out... when you've solved those problems it normally works when you run them from OpenGrok... (except from the web ui, which a lot of times comes from the fact that the webserver don't have the same environment variables set up)...

**Comment by ymnick** [comment] 2015-04-14 02:53
I have it on Linux now, all works except history and annotations. The command I run is "OPENGROK_VERBOSE=true OPENGROK_INSTANCE_BASE=/usr/opengrok EXUBERANT_CTAGS=/usr/bin/ctags GENERATE_HISTORY="-r on" ./OpenGrok index /usr/opengrok/source/" and in the output I see same warning about Perforce history:

Loading the default instance configuration ...
Logging filehandler pattern: /usr/opengrok/log/opengrok%g.%u.log
05:51:20 INFO: Scanning for repositories...
05:51:20 INFO: done invalidating repositories (took 17 ms)
05:51:20 INFO: Done scanning for repositories (0s)
05:51:20 INFO: Writing configuration to /usr/opengrok/etc/configuration.xml
05:51:20 INFO: Done...
05:51:20 INFO: Generating history cache for all repositories ...
05:51:20 INFO: Creating historycache for 1 repositories
05:51:20 INFO: Creating historycache for /usr/opengrok/source (PerforceRepository)
05:51:20 WARNING: Incremental history retrieval is not implemented for PerforceRepository.
05:51:20 WARNING: Falling back to slower full history retrieval.
05:51:20 INFO: Done historycache for /usr/opengrok/source (took 40 ms)
05:51:20 INFO: Done historycache for all repositories (took 54 ms)
05:51:20 INFO: Done...
05:51:20 INFO: Starting indexing
05:51:21 INFO: Creating historycache for /usr/opengrok/source (PerforceRepository)
05:51:21 WARNING: Incremental history retrieval is not implemented for PerforceRepository.
05:51:21 WARNING: Falling back to slower full history retrieval.
05:51:21 INFO: Done historycache for /usr/opengrok/source (took 27 ms)
05:51:21 INFO: Done indexing data of all repositories (took 889 ms)
05:51:21 INFO: Send configuration to: localhost:2424
05:51:21 INFO: Configuration update routine done, check log output for errors.
05:51:21 INFO: Total time: 1.610 seconds
05:51:21 INFO: Final Memory: 2M/15M

**Comment by tarzanek** [comment] 2015-04-14 05:10
check the log file as well
it should have more info on what commands are being run ...

**Comment by ymnick** [comment] 2015-04-14 15:49
Log has the following list of commands, all work, checked manually, except for those two:

accurev info
-bash: accurev: command not found

cleartool -version
-bash: cleartool: command not found

Full log output:

...370+0300 FINE t1 Executor.registerErrorHandler: Installing default uncaught exception handler
...589+0300 FINE t1 Executor.exec: Executing command [/usr/bin/ctags, --version] in directory /usr/opengrok/bin
...635+0300 FINE t1 Executor.exec: Finished command [/usr/bin/ctags, --version] in directory /usr/opengrok/bin
...636+0300 INFO t1 Indexer.prepareIndexer: Scanning for repositories...
...637+0300 FINE t1 Executor.exec: Executing command [accurev, info] in directory /usr/opengrok/bin
...639+0300 FINE t1 Executor.exec: Executing command [cleartool, -version] in directory /usr/opengrok/bin
...640+0300 FINE t1 Executor.exec: Executing command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...650+0300 FINE t1 Executor.exec: Finished command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...651+0300 FINE t1 Executor.exec: Executing command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...664+0300 FINE t1 Executor.exec: Finished command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...665+0300 FINE t1 Executor.exec: Executing command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...671+0300 FINE t1 Executor.exec: Finished command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...671+0300 CONFIG t1 HistoryGuru.addRepositories: Adding <org.opensolaris.opengrok.history.PerforceRepository> repository: </usr/opengrok/source>
...672+0300 FINE t1 HistoryGuru.invalidateRepositories: invalidating repositories
...674+0300 FINE t1 Executor.exec: Executing command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...687+0300 FINE t1 Executor.exec: Finished command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...687+0300 FINE t1 Executor.exec: Executing command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...694+0300 FINE t1 Executor.exec: Finished command [/usr/local/bin/p4, help] in directory /usr/opengrok/bin
...700+0300 INFO t1 Statistics.report: done invalidating repositories (took 22 ms)
...704+0300 INFO t1 Indexer.prepareIndexer: Done scanning for repositories (0s)
...709+0300 INFO t1 Indexer.prepareIndexer: Writing configuration to /usr/opengrok/etc/configuration.xml
...963+0300 INFO t1 Indexer.prepareIndexer: Done...
...963+0300 INFO t1 Indexer.prepareIndexer: Generating history cache for all repositories ...
...966+0300 INFO t1 HistoryGuru.createCacheReal: Creating historycache for 1 repositories
...976+0300 INFO t22 HistoryGuru.createCache: Creating historycache for /usr/opengrok/source (PerforceRepository)
...977+0300 WARNING t22 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
...978+0300 WARNING t22 Repository.getHistory: Falling back to slower full history retrieval.
...981+0300 FINE t22 Executor.exec: Executing command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...993+0300 FINE t22 Executor.exec: Finished command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...994+0300 FINE t22 Executor.exec: Executing command [p4, changes, -t, ...] in directory /usr/opengrok/source
...006+0300 FINE t22 Executor.exec: Finished command [p4, changes, -t, ...] in directory /usr/opengrok/source
...012+0300 INFO t22 Statistics.report: Done historycache for /usr/opengrok/source (took 36 ms)
...014+0300 INFO t1 Statistics.report: Done historycache for all repositories (took 49 ms)
...014+0300 INFO t1 Indexer.prepareIndexer: Done...
...016+0300 INFO t1 Indexer.doIndexerExecution: Starting indexing
...517+0300 INFO t27 HistoryGuru.createCache: Creating historycache for /usr/opengrok/source (PerforceRepository)
...517+0300 WARNING t27 Repository.getHistory: Incremental history retrieval is not implemented for PerforceRepository.
...518+0300 WARNING t27 Repository.getHistory: Falling back to slower full history retrieval.
...518+0300 FINE t27 Executor.exec: Executing command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...533+0300 FINE t27 Executor.exec: Finished command [/usr/local/bin/p4, dirs, *] in directory /usr/opengrok/source
...535+0300 FINE t27 Executor.exec: Executing command [p4, changes, -t, ...] in directory /usr/opengrok/source
...546+0300 FINE t27 Executor.exec: Finished command [p4, changes, -t, ...] in directory /usr/opengrok/source
...548+0300 INFO t27 Statistics.report: Done historycache for /usr/opengrok/source (took 31 ms)
...062+0300 INFO t1 Statistics.report: Done indexing data of all repositories (took 1.46 seconds)
...063+0300 INFO t1 Indexer.sendToConfigHost: Send configuration to: localhost:2424
...175+0300 INFO t1 Indexer.sendToConfigHost: Configuration update routine done, check log output for errors.
...176+0300 INFO t1 Statistics.report: Total time: 1.813 seconds
...222+0300 INFO t1 Statistics.report: Final Memory: 2M/15M

**Comment by tarzanek** [comment] 2015-04-14 19:42
webapp has to have same permissions as shell

usual hack is to index sources as user who runs tomcat ...

**Comment by ymnick** [comment] 2015-04-14 20:30
tomcat service runs as root

**Comment by tarzanek** [comment] 2015-04-15 05:21
I can try to reproduce if I will have some spare time - where can I get a perforce repo and a client for windows or debian linux? (or solaris 11?)

**Comment by ymnick** [comment] 2015-04-15 16:44
http://www.perforce.com/downloads/Perforce/Customer

**Comment by tarzanek** [comment] 2015-04-15 18:38
is there some sample repo i can test on?

**Comment by ymnick** [comment] 2015-04-15 18:42
Not that I'm aware of...

**Comment by robp85** [comment] 2015-09-15 13:59
Any word on this issue? I can't seem to get the history or annotations to work for OpenGrok 0.12.1.5 (or any version of 12, actually). My customers are highly dependent on being able to look up the history for their Perforce repositories.

**Comment by dimitkoto** [comment] 2015-09-15 15:23
Same with me, but I get the history and annotate for GIT projects only, and the SVN history/annotate disappeared. In the previous versions it was all fine.

**Comment by tarzanek** [comment] 2015-09-15 18:48
if someone can send me a sample perforce repo zipped I'd gladly test, so far I didn't have time to create a repo myself ... also this thread is about index update and got stolen for perforce issues (and now svn?) ... I guess we should open new issues and ideally I'd need some help
anyways based on above it seems our junit tests for svn are bad and we obviously miss perforce testing ... (perforce is not bundled in e.g. ubuntu we use on travis ... )

so if someone can send me a sample perforce repo zipped, I am willing to play a bit

**Comment by ymnick** [comment] 2015-09-23 00:57
I have a feeling this might be related to the repositories/projects layout issue discussed in #942. I see history files on disk, and Tomcat service user has full access to these files, but opengrok shows 'file not found' error. This is how it looks like in my setup:

/usr/opengrok/
			data/
				historycache
				index
				timestamp
				xref
			source/
				p4_depot1
				p4_depot2

**Comment by tarzanek** [comment] 2015-09-23 03:54
Yes please, if you can gzip it and share it I should be able to fix asap.

**Comment by ymnick** [comment] 2015-09-23 16:35
How can I send it to you?

**Comment by robp85** [comment] 2015-09-23 16:43
Thank you all so much for looking into this!

**Comment by tarzanek** [comment] 2015-09-23 21:13
If it's not big just mail me(my mail is in commit msgs)
If it is big can you please upload it to some public share server?

**Comment by ymnick** [comment] 2015-09-23 21:23
Sorry, I don't see it (your e-mail in commit msgs)

**Comment by vladak** [comment] 2015-09-23 21:33
You have to run `git log` on command line in order to see the mails.

**Comment by ymnick** [comment] 2015-09-23 21:52
Every day I learn something new, thank you! :)

**Comment by tarzanek** [comment] 2015-10-02 07:30
still checking it out, need a few days to push this forward, sorry :(

**Comment by ymnick** [comment] 2015-10-15 20:26
Any progress?

**Comment by robp85** [comment] 2015-12-16 19:14
Hi,

Any word on this?

**Comment by tarzanek** [comment] 2015-12-17 09:21
;) I will have a look now
early Christmas came in :-D
(or feel free to send over a pizza or flowers when in Prague
or  better yet, plant a tree in your neighborhood ... this is an expensive ticket/issue :-D )

**Comment by tarzanek** [comment] 2015-12-17 10:43
hmm, with the repo checkout it seems I miss server side ... (why is perforce still used? in the age of git/hg this SCM makes not much sense to me, oh well)
I'll try to simulate these steps:
1) get OpenGrok code checked into perforce server (helix?)
2) check it out to some local source dir
3) index the local source dir with latest trunk code

**Comment by tarzanek** [comment] 2015-12-18 15:28
@ymnick @robp85 can I get a quick set of commands what do run to push some code to my depot and then check it out to a dir ?

**Comment by robp85** [comment] 2016-01-11 17:40
Hello @tarzanek. Probably better than me typing out a bunch of commands, here is a list of them from Perforce.
https://www.perforce.com/perforce/r15.1/manuals/p4guide/chapter.usingp4.html

**Comment by ymnick** [comment] 2016-01-11 19:28
@tarzanek 
to submit new file - p4 submit -f submitunchanged -i
to sync new changes - p4 sync c:\username\p4code\workspacename\...#head

**Comment by tarzanek** [comment] 2016-01-12 12:14
@ymnick thnx, I will try it and see how it works so I can then fix any problems
a pity this couldn't be very well automated into testing suite (like we do for git/hg)

**Comment by ymnick** [comment] 2016-01-26 18:19
@tarzanek , any luck?

**Comment by tarzanek** [comment] 2016-01-27 14:56
actually I noticed @903 not being merged ... which is odd, looking at how can we merge this and if it will fix the prob you see

**Comment by tarzanek** [comment] 2016-02-01 16:05
@ymnick so I just tried on windows
I've set
set PROPERTIES="-Dorg.opensolaris.opengrok.history.perforce=C:\Program Files\Perforce\p4.exe"
and I use this variable as param to opengrok.jar , e.g.
%JAVA_HOME%\bin\java %DEBUG% %PROPERTIES% %LPROPERTIES% -jar %PROGDIR%opengrok.jar %SKIN% -p \opengrok %WA%  -U %WEBAPP% -P -W C:\var\opengrok\etc\configuration.xml  %SCAN_FOR_REPOS% -r on %MAXWORDS% -a on -v -c %EXUB_CTAGS% -s %SRC_ROOT% -d %DATA_ROOT%
rem java -jar %PROGDIR%opengrok.jar  -m %MAXWORDS% -v -c %EXUB_CTAGS% -s %SRC_ROOT% -d %DATA_ROOT%
echo %errorlevel%

**Comment by tarzanek** [comment] 2016-02-01 16:06
@ymnick and all history worked fine for me ...
I will retry incremental history now and eventually merge @dobrou @903
then I will gladly remove perforce and never use it again :)

**Comment by tarzanek** [comment] 2016-02-01 16:07
@ymnick @robp85 also note that I am doing this on latest trunk(so what will be 0.13) and NOT on 0.12 !

**Comment by tarzanek** [comment] 2016-02-01 17:04
@ymnick @robp85 also note that my scenario was very simplified - all was run by the same user (tomcat, indexing, p4d and obviously p4 client used the same user)

**Comment by robp85** [comment] 2016-02-02 16:45
@tarzanek Thank you for looking into this. I am using version 12.1.5 which, I believe, is the current released version. Do you know when version 13 might be released? I am going to attempt to use the version from the trunk for now and see if that fixes the issues I'm seeing. Do I need to create a new index/history cache with this new version? Also note, I'm using one user for tomcat, indexing and P4 commands.

I know Perforce isn't the top priority but unfortunately, I can't get away from it (company needs).

**Comment by tarzanek** [comment] 2016-02-02 17:58
Yes a reindex from scratch is needed. 2 years of dev are in 0.13 so index is changed a lot.
I am trying to get 0.13 out for past two month and my deadline is march ... so let's see if I will make it ;)

**Comment by robp85** [comment] 2016-02-02 17:58
@tarzanek I just tried to build the current Opengrok-master and I'm getting build failures during the Indexer part of the build. Is there a chance you could provide me a built copy of this so I can test version 13?

Awesome. Glad to hear it. Thank you for working on this.

**Comment by tarzanek** [comment] 2016-02-03 09:06
I think I was able to reproduce what you see
when I indexed and p4d wasn't running I got the "File not found" error

**Comment by tarzanek** [comment] 2016-02-03 09:14
I will improve the error message, anyways the cause is that indexer didn't have p4d running while indexing or couldn't access it

**Closed** 2016-02-03 13:38 UTC
Labels: question

**Comment by robp85** [comment] 2016-02-03 15:05
@tarzanek Ah, thank you Tarzanek! Hopefully your new version will be released soon and I can upgrade to it. One last thing that I've recently noticed was that the configuration.xml for a couple of my Perforce projects have been generated incorrectly. I think it's easier if I just show an example:

`<void method="add">
<object class="org.opensolaris.opengrok.history.RepositoryInfo">
<void property="directoryName">
**<string>/data/src/fu/bar/something</string>**
</void>
<void property="type">
<string>Perforce</string>
</void>
</object>
</void>`

When it should be pointing to just **/data/src/fu**. I don't know what is causing the configuration to be generated two folders below where it should be. Out of the 28 Perforce repositories I have indexed, this has happened on three of them. The Git repos I have indexed seem to work just fine.

Again, thank you so much for working on this!

**Comment by tarzanek** [comment] 2016-02-03 16:09
@robp85 I think it is detected by first file that responds to p4 command
I think perforce repository parser needs a lot of work
Feel free to look at it ... look at hg/git parser/repo and in terms of what they do you can try to do the same for p4, it certainly should make the the parser/repository more flexible!
my p4 knowledge is very limited and I have almost no interest in improving it for obvious reasons ;)
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/PerforceRepository.java
e.g. compare to 
isRepositoryFor in 
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/MercurialRepository.java

**Comment by tarzanek** [comment] 2016-02-03 16:11
@robp85 I am not sure if it makes any sense the directoryName - per code, it seems only incremental update uses it ... (and it looks like it doesn't work that much)

**Comment by robp85** [comment] 2016-02-03 16:36
@tarzanek OK. Thank you. Unfortunately, my skill in Java (or really any programming language) is pretty poor. I'll see if I can notice anything easily but I'm pretty confident I won't be able to figure it out.

**Comment by ymnick** [comment] 2016-02-03 20:08
@tarzanek thanks for solving the issue! Could you please clarify 'indexer didn't have p4d running while indexing or couldn't access it'? Indexer is sunning on a box having Perforce client tools installed (p4, p4v, etc.) while p4d is Perforce server service running and available as long as Perforce server as running, as far as I understand. Could you please let me know what I miss?

**Comment by tarzanek** [comment] 2016-02-03 22:31
Nothing is missing.
I could only reproduce this error if indexer wasn't able to talk to p4d or it was missing the repo
I tried both repo within the checkout
And remote repo.
The error happened for me if remote repo was unreachable - so no p4 service running
Try running the same commands indexer runs to troubleshoot.
Not sure if 0.12 prints them, but trunk does print them into log file.

**Comment by ymnick** [comment] 2016-02-04 00:56
Can't see anything wrong in the indexer output, expect for the 'indexDown' I see now and then, not sure if it's related:

Feb 03, 2016 8:00:02 AM org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Scanning for repositories...
Feb 03, 2016 8:00:07 AM org.opensolaris.opengrok.util.Statistics report
INFO: done invalidating repositories (took 1.547 seconds)
Feb 03, 2016 8:00:07 AM org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Done scanning for repositories (4s)
Feb 03, 2016 8:00:07 AM org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Writing configuration to C:\opengrok\configuration.xml
Feb 03, 2016 8:00:08 AM org.opensolaris.opengrok.index.Indexer prepareIndexer
INFO: Done...
Feb 03, 2016 8:00:08 AM org.opensolaris.opengrok.index.Indexer doIndexerExecution
INFO: Starting indexing
...
Feb 03, 2016 8:00:45 AM org.opensolaris.opengrok.index.IndexDatabase indexDown
...
INFO: Optimizing the index ... 
Feb 03, 2016 8:01:59 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: Optimizing the index ... 
Feb 03, 2016 8:02:09 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: done
Feb 03, 2016 8:02:16 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: Optimizing the index ... 
Feb 03, 2016 8:02:18 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: done
Feb 03, 2016 8:02:42 AM org.opensolaris.opengrok.index.IndexDatabase optimize
INFO: done

**Comment by tarzanek** [comment] 2016-02-04 05:57
That's harmless.
Is this 0.12?
Would you mind trying out the trunk?

**Comment by RabihAntoun** [comment] 2016-02-25 10:10
Hello @ymnick  your problem is caused by the file ownership of the indexed files.
Make sure tomcat:tomcat is the owner of the indexed files and the history will show again.

As for the annotate and history make sure your tomcat is launched with java 64b and with an XMX of minimum 4GB as it fails on heap space when trying to get the p4 information from the server.

my investigations required 3 full days therefore i'm happy to share with you anything i faced during this, specially that i use perforce as SCM from my side as well

**Comment by tarzanek** [comment] 2016-02-25 10:40
@RabihAntoun it seems we've done some bad documentation job based on what you say, all what you mentioned are well known things and I hoped we documented most of them in readme ... could you check https://github.com/OpenGrok/OpenGrok/blob/master/README.txt and let us know what needs fixing?
Or ideally clone the repo, do the changes, we will gladly accept docs improvements!

**Comment by UnstoppableDrew** [comment] 2019-04-25 20:54
I know this is a really old ticket, but this problem still exists. I just set up a new instance of Tomcat 8.5, and OpenGrok 1.2.6. Both Tomcat files and OpenGrok files are owned by the same user. Tomcat is running with an Xmx of 8G. This test instance has 1 Git and 1 Perforce project under the src directory. The Git project indexes and shows history perfectly, the Perforce project generates the history cache but throws file not found errors when you try to look at the history.

I've read through some of the code, but I'm not a Java guy so this is out of my area of expertise. However, I am a Perforce expert and I would be more than happy to work with the developers to give a better understanding of how it works, and set up an environment to use to develop/debug against.

**Comment by vladak** [comment] 2019-04-26 13:15
That's great, Drew.

You don't need to understand much Java in order to see what is going on in Perforce repository handling. The relevant source files are under https://github.com/oracle/opengrok/tree/master/opengrok-indexer/src/main/java/org/opengrok/indexer/history , named aptly `Perforce*.java`. Basically, it is bunch of classes that execute the `p4` command, parse its output and convert the results to one object or another.

If I understand it correctly, the main problem we are trying to tackle here is the inability to display history of a file when indexing is done. Indexer calls the `PerforceRepository#getHistory()` to retrieve the `History` object for each file. The serialized and compressed representation of this object is then stored on disk under the `historycache` directory as a `foo.gz` file. If you try to uncompress and display the contents of this file you will discover it is just a Java bean - XML file.

So, maybe you can start by bumping the log level to `ALL` and trace the container server (with `strace` if you are on Linux) to see what file is actually being accessed when accessing the history.

**Comment by gtoph** [comment] 2019-05-15 22:54
For what it's worth.  p4 history does work just fine on windows and 'mostly' fine on linux, though I think those problems are on some account access things.  I've customized some of the opengrok perforce files, but I don't think what I've done would matter too much.  I've focused mostly on windows, but here's a couple of things you might want to check:
1. Ensure tomcat service is running under an account that has access to P4
2. Each of my projects has a .p4config located in the root of them
3. I did add an '-s' option to the parser, though I"m not sure if that would matter:  cmd.add("-slti");  in PerforceHistoryParser.java
4. The other thing I thought of is perhaps it's a path issue.  In my customization, I"m converting everything to absolute paths ('toRealPath()"  type stuff - my root projects are technically all symlinks to the real project)

Not sure any of that'll help, but figured it wouldn't hurt to mention.

**Comment by cross** [comment] 2019-06-13 15:20
> 1. Ensure tomcat service is running under an account that has access to P4

I have the account indexing use P4USER env variable (and P4PORT and P4CLIENT).  Does tomcat need any access to perforce, or just the indexing operations?

> 2. Each of my projects has a .p4config located in the root of them

This is something I did not do.  Did you have each project use its own client spec?  And, how do you keep this .p4config file from being deleted (with p4 clean, or rm/p4 sync), as I assume it's not checked into  your repository.

> Not sure any of that'll help, but figured it wouldn't hurt to mention.

Thank you!  I'm looking for help in getting a bunch of perforce projects (all in the same perforce server, though arguably a small number of "repositories", but that's mostly semantic/political) working within my opengrok setup.

**Comment by gtoph** [comment] 2019-06-13 16:36
> I have the account indexing use P4USER env variable (and P4PORT and P4CLIENT). Does tomcat need any access to perforce, or just the indexing operations?

The tomcat service also needs to be running as a user with access permissions to P4 as well.  You can specify this with the "monitor tomcat" utility or just do the same thing in 'services.msc'

> This is something I did not do. Did you have each project use its own client spec? And, how do you keep this .p4config file from being deleted (with p4 clean, or rm/p4 sync), as I assume it's not checked into your repository.

Yes, every project I have is it's own client spec.  Unfortunately, I"m not a P4 admin in our setup, but I'm assuming there is a way to filter the p4config file (similar to git .ignore or something) for any p4 operations.

All the P4 commands (like P4 dir that opengrok uses) will go back to this root .p4config file to get the client spec which allows them to work on the given project

**Comment by cross** [comment] 2019-06-13 18:05
> The tomcat service also needs to be running as a user with access permissions to P4 as well. You can specify this with the "monitor tomcat" utility or just do the same thing in 'services.msc'

Thanks, but why?  If it needs it, I can make that happen, I just don't know what it needs it for.  AFAIK my tomcat is running without it, and information is available from the index that was created which had that access at the time.

**Comment by gtoph** [comment] 2019-06-13 18:08
> 
> 
> > The tomcat service also needs to be running as a user with access permissions to P4 as well. You can specify this with the "monitor tomcat" utility or just do the same thing in 'services.msc'
> 
> Thanks, but why? If it needs it, I can make that happen, I just don't know what it needs it for. AFAIK my tomcat is running without it, and information is available from the index that was created which had that access at the time.

I forgot the exact commands involved, but the indexer doesn't actually get the full history.  If you look in the \history folder, you'll just see a summary kinda thing for each file.  When you actually view the history, Tomcat will run P4 commands to get the whole shabang so you can compare versions and all that.  So that's why it needs to be running as a user with P4 access.

**Comment by cross** [comment] 2019-06-13 18:30
Okay. I considered that possible, but I at least seem to have the full history records.  I may not be able to diff between revisions, I think I saw some issues with trying that.  I looked in log files to see if I could find errors being thrown, to indicate p4 commands running and failing, but didn't find any.  Any idea which logs these would be in?  Of course, I'm running in Linux under tomcat, so I'm not sure if you could point me as I don't know how different your windows environment is...
If I can see what's failing, I can fix it.  :-)  An on the other thread, I'm still working out the whole which/how many p4 client specs I'll need, so I'll want to resolve that first.

**Comment by cross** [comment] 2019-06-14 16:59
Okay.  I have found that I seem not to be getting correct diffs from opengrok for some (all?) of my perforce repository.  It seems to show either no differences, or that the whole file is new.  I assume this may be a result of tomcat not operating with the right setup for talking to the perforce repository.

I tried increasing the logging in /etc/tomcat8/logging.properties but see no effect.  I am not very familiar with java logging and worry there can be a bazillion different setups and files.  :-)  @vladak maybe you can help me figure out how to get better logging to try to diagnose why my diffs for perforce files shows either "No differences found!" or a wholly new file?  I'm sure it's failing to retrieve data from perforce, but I don't have the logs to figure out what's wrong...

**Comment by vladak** [comment] 2019-06-17 12:39
For debugging web app issues via logging, I added this line into the `logging.properties` file under Tomcat's config directory:
```
org.opengrok.level = ALL
```
and made sure the file is actually used:
```
# svcs -p tomcat8
STATE          STIME    FMRI
online         Apr_12   svc:/network/http:tomcat8
               Apr_12        1321 java
# pargs 1321
1321:   /usr/jdk/instances/jdk1.8.0/bin/java -Djava.util.logging.config.file=/var/tomca
argv[0]: /usr/jdk/instances/jdk1.8.0/bin/java
argv[1]: -Djava.util.logging.config.file=/var/tomcat8/conf/logging.properties
argv[2]: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
argv[3]: -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
argv[4]: -Djdk.tls.ephemeralDHKeySize=2048
argv[5]: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
argv[6]: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
argv[7]: -Dignore.endorsed.dirs=
argv[8]: -classpath
argv[9]: /usr/tomcat8/bin/bootstrap.jar:/usr/tomcat8/bin/tomcat-juli.jar
argv[10]: -Dcatalina.base=/var/tomcat8
argv[11]: -Dcatalina.home=/usr/tomcat8
argv[12]: -Djava.io.tmpdir=/var/tomcat8/temp
argv[13]: org.apache.catalina.startup.Bootstrap
argv[14]: start
```

**Comment by vladak** [comment] 2019-06-17 12:58
The way diff'ing works is that `diff.jsp` calls `PageConfig#getDiffData()` which in turn calls `HistoryGuru.getInstance().getRevision()` for both new and old file. This call bubbles down to `PerforceRepository#getHistoryGet()` that will execute a `p4` command. I see that the code has a curious note about evaluating the return code from the command: https://github.com/oracle/opengrok/blob/4a1cfebea028a07cd62a4e613864e7beee5581c8/opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java#L103-L119
so perhaps this needs to be addressed first.
